Repository AnthoninHelias/qcmreactjs, pull requests merged in 2024-06, with the labels that each got.

#77 Affichage des reponses
  src/pages/App.css
  src/pages/App.tsx
  src/pages/QuestionsReponses.tsx
  src/pages/Score.tsx
Labels: review

#79 Gestion score
  src/pages/QuestionsReponses.tsx
Labels: review

#81 ajout hook
  src/hooks/useApi.ts
  src/pages/QuestionsReponses.tsx
Labels: review

#82 Test unitaire + workflow
  .eslintignore
  .github/workflows/test.js.yml
  babel.config.cjs
  jest.config.js
  junit.xml
  package-lock.json
  package.json
  src/components/TimerComponent.tsx
  src/increment.spec.ts
  src/increment.ts
  src/pages/App.test.tsx
  src/pages/QuestionReponse.test.tsx
  src/pages/QuestionsReponses.tsx
  src/pages/Score.test.tsx
  tsconfig.json
  yarn.lock
Labels: review, bugFix

#84 Update README.md
  README.md
Labels: documentation, review

#85 Update README.md
  README.md
Labels: review

#86 Update READ.me
  README.md
Labels: documentation, review

#87 Update README.md
  README.md
Labels: documentation, review

#88 Update README.md
  README.md
Labels: review

#89 Ajout du logo de quizz
  public/index.html
  public/logoQuizz.jpeg
  src/pages/App.tsx
  src/pages/QuestionsReponses.tsx
Labels: review
